/**
 * ESLint flat config for Next.js 15 + TypeScript.
 *
 * Generated as part of Phase 4 migration off the deprecated `next lint`
 * command (removed in Next 16). Uses FlatCompat to bridge the legacy
 * `next/core-web-vitals` and `next/typescript` shareable configs into
 * the new flat-config format that ESLint v9 expects.
 *
 * Run with: `npm run lint` (which now invokes `eslint .` directly).
 */
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname  = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // Bring in the standard Next.js + TypeScript rule sets.
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  // Project-wide ignore patterns. Keep this list tight — anything inside
  // these paths is skipped by lint and won't fail CI.
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "node_modules/**",
      "android/**",
      "ios/**",
      "mobile/dist/**",
      "supabase/migrations/**",
      "public/sw.js",
      "scripts/**",
      "*.config.mjs",
      "*.config.js",
      "*.config.ts",
      // Generated TS files from supabase gen types
      "src/types/database.ts",
      // Auto-generated by Next.js — uses triple-slash references we can't change
      "next-env.d.ts",
    ],
  },

  // Per-project rule tweaks. Keep this minimal — broader cleanup is out
  // of scope for Phase 4. Add ONLY what's needed to keep the existing
  // codebase passing without changing behavior.
  {
    rules: {
      // The codebase uses a fair amount of `// eslint-disable-next-line
      // @typescript-eslint/no-explicit-any` for Supabase typed-RPC casts
      // until generated types catch up. Surfacing those as errors would
      // be a wide refactor, which Phase 4 explicitly avoids.
      "@typescript-eslint/no-explicit-any": "warn",
      // Same reasoning — many server-action files have intentional
      // `any` shapes for the RLS-bypass admin client.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default eslintConfig;
